const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Plugins.Text,
		C3.Plugins.Audio,
		C3.Plugins.Mouse,
		C3.Plugins.Button,
		C3.Plugins.Touch,
		C3.Behaviors.Platform,
		C3.Behaviors.Tween,
		C3.Behaviors.Bullet,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Touch.Cnds.OnTapGesture,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Plugins.Sprite.Acts.RotateTowardAngle,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Plugins.Button.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Cnds.EveryTick
	];
};
self.C3_JsPropNameTable = [
	{MuteButton: 0},
	{OwlSt: 0},
	{START: 0},
	{Effect: 0},
	{BGSTrat: 0},
	{GameName: 0},
	{DownPipe: 0},
	{DownpipeSpawn: 0},
	{ScorePane: 0},
	{ScoreSpawn: 0},
	{Solid: 0},
	{Toppipe: 0},
	{toppipeSpawn: 0},
	{Cumpi: 0},
	{PlayAgain: 0},
	{Score: 0},
	{GMSCORE: 0},
	{isPaused: 0},
	{ClickToStart: 0},
	{Audio: 0},
	{Mouse: 0},
	{Replay: 0},
	{Touch: 0},
	{isHit: 0},
	{isFlying: 0},
	{Platform: 0},
	{Owl: 0},
	{Ground: 0},
	{BGLibary: 0},
	{GrassGround: 0},
	{Spike: 0},
	{Tween: 0},
	{TransitionFade: 0},
	{ScoreNumberDisplay: 0},
	{Bullet: 0},
	{Pipes: 0},
	{Dead: 0},
	{IsMuted: 0},
	{HIScore: 0}
];

self.InstanceType = {
	MuteButton: class extends self.ISpriteInstance {},
	OwlSt: class extends self.ISpriteInstance {},
	START: class extends self.ISpriteInstance {},
	Effect: class extends self.ISpriteInstance {},
	BGSTrat: class extends self.ISpriteInstance {},
	GameName: class extends self.ISpriteInstance {},
	DownPipe: class extends self.ISpriteInstance {},
	DownpipeSpawn: class extends self.ISpriteInstance {},
	ScorePane: class extends self.ISpriteInstance {},
	ScoreSpawn: class extends self.ISpriteInstance {},
	Toppipe: class extends self.ISpriteInstance {},
	toppipeSpawn: class extends self.ISpriteInstance {},
	Cumpi: class extends self.ISpriteInstance {},
	PlayAgain: class extends self.ISpriteInstance {},
	Score: class extends self.ITextInstance {},
	GMSCORE: class extends self.ITextInstance {},
	ClickToStart: class extends self.ITextInstance {},
	Audio: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Replay: class extends self.IButtonInstance {},
	Touch: class extends self.IInstance {},
	Owl: class extends self.ISpriteInstance {},
	Ground: class extends self.ISpriteInstance {},
	BGLibary: class extends self.ISpriteInstance {},
	GrassGround: class extends self.ISpriteInstance {},
	Spike: class extends self.ISpriteInstance {},
	TransitionFade: class extends self.ISpriteInstance {},
	ScoreNumberDisplay: class extends self.ITextInstance {},
	Pipes: class extends self.ISpriteInstance {},
	Dead: class extends self.ISpriteInstance {}
}